version: "3.9"
services:

  api:
    build: ./api
    ports:
      - "5543:${APIPORT}"
    environment:
    - PG_CONNECTION_STRING=postgress://${POSTGRES_USER}:${POSTGRES_PASSWORD}@pg:5432/${POSTGRES_DB}
    - POSTGRES_PASSWORD
    - POSTGRES_USER
    - POSTGRES_DB
    volumes:
     - ./api/src:/usr/app/src
    depends_on:
     - pg

  pg:
   container_name: ${POSTGRES_DB}
   image: postgres
   ports:
    - 5432:5432
   volumes:
    - ./pg/src:/usr/app/src
   environment:
    - POSTGRES_PASSWORD
    - POSTGRES_USER
    - POSTGRES_DB
