version: "3.9"
services:

  api:
    build: ./
    image: crshlab/api_test:0.1
    ports:
      - "8000:8000"
    environment:
    - PG_CON=postgress://${POSTGRES_USER}:${POSTGRES_PASSWORD}@pg:5433/${POSTGRES_DB}
     - PORT
    volumes:
     - ./api/src:/usr/app/src
    depends_on:
     - pg

  pg:
   image: postgres
   ports:
    - 5432:5432
   volumes:
    - ./pg/src:/usr/app/src
   environment:
    - POSTGRES_PASSWORD
    - POSTGRES_USER
    - POSTGRES_DB
